apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.application.name }} 
  replicas: {{ .Values.application.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name }}
    spec:
      containers:
        - name: {{ .Values.application.containers.name }}
          image: {{ .Values.application.containers.repo }}:{{ .Values.application.containers.tag | default "latest" }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}

